# Trimming and Filtering

```{r, include = FALSE}

knitr::opts_chunk$set(
  engine = list('zsh'),
  engine.path = list('/bin/zsh'),
  engine.opts = list(zsh = "-i")
                      )

```


## Cleaning reads

In the previous episode, we took a high-level look at the quality
of each of our samples using FastQC. We visualized per-base quality
graphs showing the distribution of read quality at each base across
all reads in a sample and extracted information about which samples
fail which quality checks. Some of our samples failed quite a few quality metrics used by FastQC. This does not mean,
though, that our samples should be thrown out! It is very common to have some quality metrics fail, and this may or may not be a problem for your downstream application. For our variant calling workflow, we will be removing some of the low quality sequences to reduce our false positive rate due to sequencing error.

We will use a program called
[Trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic) to
filter poor quality reads and trim poor quality bases from our samples.

## Trimmomatic options

Trimmomatic has a variety of options to trim your reads. If we run the following command, we can see some of our options.


```{zsh, eval=FALSE, engine="sh"}

cd ~/dc_workshop/data/untrimmed_fastq

source $HOME/miniconda3-intel/bin/activate
conda activate variant
trimmomatic

```

Which will give you the following output:

Usage: 
       PE [-version] [-threads <threads] [-phred33|-phred64] [-trimlog <trimLogFile] [-summary <statsSummaryFile] [-quiet] [-validatePairs] [-basein <inputBase| <inputFile1<inputFile2] [-baseout <outputBase| <outputFile1P<outputFile1U<outputFile2P<outputFile2U] <trimmer1...
   or: 
       SE [-version] [-threads <threads] [-phred33|-phred64] [-trimlog <trimLogFile] [-summary <statsSummaryFile] [-quiet] <inputFile<outputFile<trimmer1...
   or: 
       -version

This output shows us that we must first specify whether we have paired end (`PE`) or single end (`SE`) reads.
Next, we specify what flag we would like to run. For example, you can specify `threads` to indicate the number of
processors on your computer that you want Trimmomatic to use. In most cases using multiple threads (processors) can help to run the trimming faster. These flags are not necessary, but they can give you more control over the command. The flags are followed by positional arguments, meaning the order in which you specify them is important. 
In paired end mode, Trimmomatic expects the two input files, and then the names of the output files. These files are described below. While, in single end mode, Trimmomatic will expect 1 file as input, after which you can enter the optional settings and lastly the name of the output file.

| option    | meaning |
| ------- | ---------- |
|  \<inputFile1 | Input reads to be trimmed. Typically the file name will contain an `_1` or `_R1` in the name.|
| \<inputFile2| Input reads to be trimmed. Typically the file name will contain an `_2` or `_R2` in the name.|
|  \<outputFile1P| Output file that contains surviving pairs from the `_1` file. |
|  \<outputFile1U| Output file that contains orphaned reads from the `_1` file. |
|  \<outputFile2P| Output file that contains surviving pairs from the `_2` file.|
|  \<outputFile2U| Output file that contains orphaned reads from the `_2` file.|

The last thing trimmomatic expects to see is the trimming parameters:

| step   | meaning |
| ------- | ---------- |
| `ILLUMINACLIP` | Perform adapter removal. |
| `SLIDINGWINDOW` | Perform sliding window trimming, cutting once the average quality within the window falls below a threshold. |
| `LEADING`  | Cut bases off the start of a read, if below a threshold quality.  |
| `TRAILING` |  Cut bases off the end of a read, if below a threshold quality. |
| `CROP`  |  Cut the read to a specified length. |
| `HEADCROP` |  Cut the specified number of bases from the start of the read. |
| `MINLEN`  |  Drop an entire read if it is below a specified length. |
| `TOPHRED33` | Convert quality scores to Phred-33.  |
| `TOPHRED64` |  Convert quality scores to Phred-64. |



We will use only a few of these options and trimming steps in our
analysis. It is important to understand the steps you are using to
clean your data. For more information about the Trimmomatic arguments
and options, see [the Trimmomatic manual](http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf).

However, a complete command for Trimmomatic will look something like the command below. This command is an example and will not work, as we do not have the files it refers to:


trimmomatic PE -threads 4 SRR_1056_1.fastq SRR_1056_2.fastq  \
              SRR_1056_1.trimmed.fastq SRR_1056_1un.trimmed.fastq \
              SRR_1056_2.trimmed.fastq SRR_1056_2un.trimmed.fastq \
              ILLUMINACLIP:SRR_adapters.fa SLIDINGWINDOW:4:20


In this example, we have told Trimmomatic:

| code   | meaning |
| ------- | ---------- |
| `PE` | that it will be taking a paired end file as input |
| `-threads 4` | to use four computing threads to run (this will speed up our run) |
| `SRR_1056_1.fastq` | the first input file name |
| `SRR_1056_2.fastq` | the second input file name |
| `SRR_1056_1.trimmed.fastq` | the output file for surviving pairs from the `_1` file |
| `SRR_1056_1un.trimmed.fastq` | the output file for orphaned reads from the `_1` file |
| `SRR_1056_2.trimmed.fastq` | the output file for surviving pairs from the `_2` file |
| `SRR_1056_2un.trimmed.fastq` | the output file for orphaned reads from the `_2` file |
| `ILLUMINACLIP:SRR_adapters.fa`| to clip the Illumina adapters from the input file using the adapter sequences listed in `SRR_adapters.fa` |
|`SLIDINGWINDOW:4:20` | to use a sliding window of size 4 that will remove bases if their phred score is below 20 |

## Multi-line commands 

Some of the commands we ran in this lesson are long! When typing a long 
command into your terminal, you can use the `\` character
to separate code chunks onto separate lines. This can make your code more readable.

## Running Trimmomatic

Now we will run Trimmomatic on our data. To begin, navigate to your `untrimmed_fastq` data directory:

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq

```


We are going to run Trimmomatic on one of our paired-end samples. 
While using FastQC we saw that Nextera adapters were present in our samples. 
The adapter sequences came with the installation of trimmomatic, so we will first copy these sequences into our current directory.

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq/
cp -R ~/miniconda3-intel/pkgs/trimmomatic-0.36-6/share/trimmomatic-0.36-6/adapters/NexteraPE-PE.fa ~/dc_workshop/data/untrimmed_fastq/

```

We will also use a sliding window of size 4 that will remove bases if their
phred score is below 20 (like in our example above). We will also
discard any reads that do not have at least 25 bases remaining after
this trimming step. Three additional pieces of code are also added to the end
of the ILLUMINACLIP step. These three additional numbers (2:40:15) tell
Trimmimatic how to handle sequence matches to the Nextera adapters. A detailed 
explanation of how they work is advanced for this particular lesson. For now we
will use these numbers as a default and recognize they are needed to for Trimmomatic
to run properly. This command will take a few minutes to run.

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq

source $HOME/miniconda3-intel/bin/activate
conda activate variant
trimmomatic PE SRR2584863_1.fastq.gz SRR2584863_2.fastq.gz \
                SRR2584863_1.trim.fastq.gz SRR2584863_1un.trim.fastq.gz \
                SRR2584863_2.trim.fastq.gz SRR2584863_2un.trim.fastq.gz \
                SLIDINGWINDOW:4:20 MINLEN:25 ILLUMINACLIP:NexteraPE-PE.fa:2:40:15
                
```

## Exercise

Use the output from your Trimmomatic command to answer the
following questions.

1) What percent of reads did we discard from our sample?
2) What percent of reads did we keep both pairs?

## Solution


You may have noticed that Trimmomatic automatically detected the
quality encoding of our sample. It is always a good idea to
double-check this or to enter the quality encoding manually.

We can confirm that we have our output files:

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq/
 ls SRR2584863*

```

The output files are also FASTQ files. It should be smaller than our
input file, because we have removed reads. We can confirm this:

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq/
ls -lh SRR2584863* 
gunzip -f -dk SRR2584863_1.trim.fastq.gz
gunzip -f -dk SRR2584863_2.trim.fastq.gz
gunzip -f -dk SRR2584863_1.fastq.gz
gunzip -f -dk SRR2584863_2.fastq.gz
ls -lh SRR2584863* 

```


Let's look at how much trimming occured on our SRR2584863_1.trim.fastq.gz
SRR2584863_2.trim.fastq.gz files. 426M and 383M, 134, , 131smaller than their
original size of 545M. So it looks like more trimming occured for the 
SRR2584863_2.trim.fastq.gz file, 472 427, 

We have just successfully run Trimmomatic on one of our FASTQ files! 
However, there is some bad news. Trimmomatic can only operate on
one sample at a time and we have more than one sample. The good news
is that we can use a `for` loop to iterate through our sample files
quickly! 

We unzipped one of our files before to work with it, let's compress it again before we run our for loop.

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq/
gzip -f SRR2584863_1.fastq 

```

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq/

source $HOME/miniconda3-intel/bin/activate
conda activate variant
for infile in *_1.fastq.gz
do
  base=$(basename ${infile} _1.fastq.gz)
  trimmomatic PE ${infile} ${base}_2.fastq.gz \
               ${base}_1.trim.fastq.gz ${base}_1un.trim.fastq.gz \
               ${base}_2.trim.fastq.gz ${base}_2un.trim.fastq.gz \
               SLIDINGWINDOW:4:20 MINLEN:25 ILLUMINACLIP:NexteraPE-PE.fa:2:40:15 
done

```

Go ahead and run the for loop. It should take a few minutes for
Trimmomatic to run for each of our four input files. Once it is done
running, take a look at your directory contents. You will notice that even though we ran Trimmomatic on file `SRR2584863_1` before running the for loop, there is only one set of files for it. Because we matched the ending `_1.fastq.gz`, we re-ran Trimmomatic on this file, overwriting our first results. That is ok, but it is good to be aware that it happened.

```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq/
ls

```
## Exercise

We trimmed our fastq files with Nextera adapters, 
but there are other adapters that are commonly used.
What other adapter files came with Trimmomatic?

## Solution




We have now completed the trimming and filtering steps of our quality
control process! Before we move on, let's move our trimmed FASTQ files
to a new subdirectory within our `data/` directory.



```{zsh, engine.opts="-i"}

cd ~/dc_workshop/data/untrimmed_fastq
mkdir -p ../trimmed_fastq
mv *.trim* ../trimmed_fastq
cd ../trimmed_fastq
ls -lah

```

## Bonus exercise (advanced)

Now that our samples have gone through quality control, they should perform
better on the quality tests run by FastQC. Go ahead and re-run
FastQC on your trimmed FASTQ files and visualize the HTML files
to see whether your per base sequence quality is higher after
trimming. Save the HTML files in ~/dc_workshop/fastqc_html/trimmed, 
then take a look at the html files in your browser.

## Solution


